apiVersion: apps/v1
kind: Deployment
metadata:
  name: abcapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abcapp
  template:
    metadata:
      labels:
        app: abcapp
    spec:
      containers:
        - name: abcapp
          image: rafavale/abcapp:1.0
          ports:
            - containerPort: 8080

